service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  versionFunction: false
  stage: "dev"
  region : "ap-south-1"
  httpApi:
    cors: true

functions:
  signup:
    handler: app/handler.SignUp
    events:
      - httpApi:
          path: /signup
          method: post
  signin:
    handler: app/handler.SignIn
    events:
      - httpApi:
          path: /signin
          method: post
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: post
  profile:
    handler: app/handler.Profile
    events:
      - httpApi:
          path: /profile
          method: post
      - httpApi:
          path: /profile
          method: put
      - httpApi:
          path: /profile
          method: get
  cart:
    handler: app/handler.Cart
    events:
      - httpApi:
          path: /cart
          method: post
      - httpApi:
          path: /cart
          method: put
      - httpApi:
          path: /cart
          method: get
  payment:
    handler: app/handler.Payment
    events:
      - httpApi:
          path: /payment
          method: post
      - httpApi:
          path: /payment
          method: put
      - httpApi:
          path: /payment
          method: get


plugins:
  - serverless-offline
  - serverless-plugin-typescript